name: Semantic Release (Node)
inputs:
  node-version:
    description: "NodeJS version"
    required: false
    default: "24"
  enable-trusted-publisher:
    description: "Enable trusted publisher method to publish code"
    required: false
    default: "true"
  npm-token-path:
    description: "The path of NPM token"
    required: false
    default: "op://DevOps/NPM Token/credential"
  github-token-path:
    description: "The path of GitHub token"
    required: false
    default: "op://DevOps/Git PAT - StoneHome - Action/credential"
  onepass-token:
    description: "1password connect token"
    required: true
  kubernetes-mode:
    description: "enable kubernetes mode, meaning that this action run on a host with ARC kubernetes mode"
    required: false
    default: "false"
  use-unified-semantic-version:
    description: "Use unified semantic release version"
    required: false
    default: "true"

# ===========================================================================
# Required Permission
#permissions:
#  contents: read
# ===========================================================================

runs:
  using: composite
  steps:
    - name: Setup 1Password
      uses: stone-home/Action-Stone-DevOps/.github/actions/setup-1password@trunk
      with:
        onepass-token: ${{ inputs.onepass-token }}
        kubernetes-mode: ${{ inputs.kubernetes-mode }}

    - name: Get Bot Token
      id: get-token
      uses: stone-home/Action-Stone-DevOps/.github/actions/load-github-token@trunk
      with:
        secret-path: ${{ inputs.github-token-path }}
        kubernetes-mode: ${{ inputs.kubernetes-mode }}
        onepass-token: ${{ inputs.onepass-token }}

    - name: Get NPM Token
      id: get-npm-token
      if: ${{ inputs.enable-trusted-publisher == 'false' }}
      uses: stone-home/Action-Stone-DevOps/.github/actions/load-github-token@trunk
      with:
        secret-path: ${{ inputs.npm-token-path }}
        kubernetes-mode: ${{ inputs.kubernetes-mode }}
        onepass-token: ${{ inputs.onepass-token }}

    - name: Setup NodeJS
      uses: stone-home/Action-Stone-DevOps/.github/actions/setup-nodejs@trunk
      with:
        node-version: ${{ inputs.node-version }}

    - name: Build
      shell: bash
      run: |
        npm run build
      
    - name: Install Semantic Release
      description: "Override Sementic Release Version"
      if: ${{ inputs.use-unified-semantic-version == 'true' }}
      uses: stone-home/Action-Stone-DevOps/.github/actions/install-semantic-release@trunk

    - name: Semantic Release
      shell: bash
      run: npx semantic-release@25.0.2
      env:
        GITHUB_TOKEN: ${{ steps.get-token.outputs.token }}
        NPM_TOKEN: ${{ inputs.enable-trusted-publisher == 'true' && 'dummy_token' || steps.get-npm-token.outputs.token}}
