name: Semantic Release (Basic)
description: "Execute a basic release process, like bash or other scripts"
inputs:
  node-version:
    description: "NodeJS version"
    required: false
    default: "24"
  onepass-token:
    description: "OnePassword Token"
    required: true
  github-token-path:
    description: "GitHub PAT secret path in Onepassword"
    required: false
    default: "op://DevOps/Git PAT - StoneHome - Action/credential"
  kubernetes-mode:
    description: "enable kubernetes mode, meaning that this action run on a host with ARC kubernetes mode"
    required: false
    default: "false"
  use-unified-semantic-version:
    description: "Use unified semantic release version"
    required: false
    default: "true"

# ===========================================================================
# Required Permission
#permissions:
#  contents: read
# ===========================================================================

runs:
  using: "composite"
  steps:
    - name: Setup NodeJS
      uses: stone-home/Action-Stone-DevOps/.github/actions/setup-nodejs@trunk
      with:
        node-version: ${{ inputs.node-version }}
        install-dependencies: "false"

    - name: Setup 1Password
      uses: stone-home/Action-Stone-DevOps/.github/actions/setup-1password@trunk
      with:
        onepass-token: ${{ inputs.onepass-token }}
        kubernetes-mode: ${{ inputs.kubernetes-mode }}

    - name: Get Bot Token
      id: get-token
      uses: stone-home/Action-Stone-DevOps/.github/actions/load-github-token@trunk
      with:
        secret-path: ${{ inputs.github-token-path }}
        kubernetes-mode: ${{ inputs.kubernetes-mode }}
        onepass-token: ${{ inputs.onepass-token }}
    
    - name: Install Semantic Release
      if: ${{ inputs.use-unified-semantic-version == 'true' }}
      uses: stone-home/Action-Stone-DevOps/.github/actions/install-semantic-release@trunk

    - name: Semantic Release
      shell: bash
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ steps.get-token.outputs.token }}
