name: Semantic Release (LaTeX)
inputs:
  node-version:
    description: "NodeJS version"
    required: false
    default: "24"
  github-token-path:
    description: "The path of GitHub token"
    required: false
    default: "op://DevOps/Git PAT - StoneHome - Action/credential"
  onepass-token:
    description: "1password connect token"
    required: true
  kubernetes-mode:
    description: "enable kubernetes mode, meaning that this action run on a host with ARC kubernetes mode"
    required: false
    default: "false"
  use-unified-semantic-version:
    description: "Use unified semantic release version"
    required: false
    default: "true"

# ===========================================================================
# Required Permission
#permissions:
#  contents: read
# ===========================================================================

runs:
  using: composite
  steps:
    # 1. Setup Node (Required for Semantic Release tool only)
    - name: Setup NodeJS
      uses: stone-home/Action-Stone-DevOps/.github/actions/setup-nodejs@trunk
      with:
        node-version: ${{ inputs.node-version }}

    # 2. Setup LaTeX (The Heavy Logic)
    - name: Cache TeX Live
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-texlive-latest
        path: /usr/local/texlive

    - name: Install TeX Live
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-full

    # 3. Auth
    - name: Setup 1Password
      uses: stone-home/Action-Stone-DevOps/.github/actions/setup-1password@trunk
      with:
        onepass-token: ${{ inputs.onepass-token }}
        kubernetes-mode: ${{ inputs.kubernetes-mode }}

    - name: Get Bot Token
      id: get-token
      uses: stone-home/Action-Stone-DevOps/.github/actions/load-github-token@trunk
      with:
        secret-path: ${{ inputs.github-token-path }}
        kubernetes-mode: ${{ inputs.kubernetes-mode }}
        onepass-token: ${{ inputs.onepass-token }}

    # 4. Release (Semantic Release will likely run latex build plugins here)
    - name: Install Semantic Release
      if: ${{ inputs.use-unified-semantic-version == 'true' }}
      uses: stone-home/Action-Stone-DevOps/.github/actions/install-semantic-release@trunk

    - name: Fetch DevOps scripts
      uses: actions/checkout@v4
      with:
        repository: stone-home/Action-Stone-DevOps
        ref: trunk
        path: .devops
    
    - name: Semantic Release
      shell: bash
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ steps.get-token.outputs.token }}
