name: "Setup Python & Poetry"
description: "Sets up Python, installs Poetry, and configures caching"
inputs:
  python-version:
    description: "Version of Python to use"
    required: true
    default: "3.12"
  poetry-version:
    description: "Version of Poetry to use"
    required: true
    default: "2.5.1"
  kubernetes-mode:
    description: "enable kubernetes mode, meaning that this action run on a host with ARC kubernetes mode"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Install pipx
      if: ${{ inputs.kubernetes-mode == 'true' }}
      shell: bash
      run: |
        apt update
        apt install -y pipx
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install poetry
      uses: abatilo/actions-poetry@v3
      if: ${{ inputs.kubernetes-mode != 'true' }}
      with:
        poetry-version: ${{ inputs.poetry-version }}

    - name: Install Poetry
      if: ${{ inputs.kubernetes-mode == 'true' }}
      shell: bash
      run: |
        pipx install "poetry==${{ inputs.poetry-version }}"

    - name: Setup Poetry config
      shell: bash
      run: |
        poetry config virtualenvs.create true --local
        poetry config virtualenvs.in-project true --local

    - uses: actions/cache@v4
      name: Cache virtual environment
      with:
        path: ./.venv
        key: venv-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles('poetry.lock') }}
